# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "1"
members = [
    "crates/logging",
    "crates/models",
    "crates/service",
    "tools/http_health_checker",
]

[profile.release]
lto = true
strip = true
