---
# Contains the minimum required services to run the application.

services:
    postgres:
        image: app_postgres:latest
        build:
            context: ../..
            dockerfile: infrastructure/docker/postgres/Dockerfile
            tags: ["app_postgres:latest"]
        container_name: app_postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            READWRITE_USER: ${POSTGRES_READWRITE_USER}
            READWRITE_PASSWORD: ${POSTGRES_READWRITE_PASSWORD}
            READONLY_USER: ${POSTGRES_READONLY_USER}
            READONLY_PASSWORD: ${POSTGRES_READONLY_PASSWORD}
        networks:
            - net
        ports:
            - "${POSTGRES_PORT}:5432"
        restart: on-failure
        volumes:
            - "postgres:/var/lib/postgresql/data"

    migrate:
        image: app_sqlx:latest
        build:
            context: ../..
            dockerfile: infrastructure/docker/postgres_migration/Dockerfile
            tags: ["app_sqlx:latest"]
        depends_on:
          postgres:
            condition: service_started
        container_name: app_database_migration
        command: sqlx migrate run
        volumes:
        - ./crates/database/migrations/:/migrations
        environment:
            DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable"


networks:
    net:

volumes:
    postgres:
