---
# Contains the minimum required services to run the application.

services:
    postgres:
        image: app_postgresql:latest
        build:
            context: ../..
            dockerfile: infrastructure/docker/postgres/Dockerfile
            tags: ["app_postgresql:latest"]
        container_name: app_postgresql
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            READWRITE_USER: ${POSTGRES_READWRITE_USER}
            READWRITE_PASSWORD: ${POSTGRES_READWRITE_PASSWORD}
            READONLY_USER: ${POSTGRES_READONLY_USER}
            READONLY_PASSWORD: ${POSTGRES_READONLY_PASSWORD}
        networks:
            - net
        ports:
            - "${POSTGRES_PORT}:5432"
        # restart: on-failure
        # volumes:
        #     - "postgres:/var/lib/postgresql/data"

    migrate:
        image: nxyt/sqlx-cli
        depends_on:
          postgres:
            condition: service_healthy
        container_name: app_database_migration
        command: migrate run
        volumes:
        - ./:/migrations
        environment:
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=enable


networks:
    net:

volumes:
    postgres:
