---
# Contains the minimum required services to run the application.

services:
    postgres:
        image: app_postgresql:latest
        build:
            context: ../..
            dockerfile: infrastructure/docker/postgres/Dockerfile
            tags: ["app_postgresql:latest"]
        container_name: app_postgresql
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            READWRITE_USER: ${POSTGRES_READWRITE_USER}
            READWRITE_PASSWORD: ${POSTGRES_READWRITE_PASSWORD}
            READONLY_USER: ${POSTGRES_READONLY_USER}
            READONLY_PASSWORD: ${POSTGRES_READONLY_PASSWORD}
        networks:
            - net
        ports:
            - "${POSTGRES_PORT}:5432"
        # restart: on-failure
        # volumes:
        #     - "postgres:/var/lib/postgresql/data"

networks:
    net:

volumes:
    postgres:
