[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "env"] }
tracing = "0.1.44"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "*"
thiserror = "2.0.17"
