server:
  address: tcp://0.0.0.0:9091

log:
  level: "debug"

totp:
  issuer: "authelia.com"

identity_validation:
  reset_password:
    jwt_secret: "a_very_important_secret"

authentication_backend:
  ldap:
    implementation: "lldap"
    address: "ldap://lldap:3890"
    base_dn: "DC=example,DC=com"
    user: "UID=admin,OU=people,DC=example,DC=com"
    password: "password"

# authentication_backend:
#   ldap:
#     implementation: custom
#     address: ldap://lldap
#     base_dn: dc=example,dc=com
#     additional_users_dn: ou=users
#     additional_groups_dn: ou=groups
#     user: cn=admin,dc=example,dc=com
#     password: admin
#     attributes:
#       username: uid
#     users_filter: "(&({username_attribute}={input})(objectClass=person))"
#     groups_filter: "(member={dn})"

access_control:
  default_policy: deny
  rules:
    - domain: "*.example.com"
      policy: one_factor

session:
  secret: "insecure_session_secret"
  cookies:
    - name: "authelia_session"
      domain: "example.com" # Should match whatever your root protected domain is
      authelia_url: "https://authelia.example.com"
      expiration: "1 hour"
      inactivity: "5 minutes"

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: a_storage_encryption_key

notifier:
  filesystem:
    filename: /config/notification.txt
