server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: a_very_secret_jwt_key

authentication_backend:
  ldap:
    implementation: custom
    address: ldap://lldap
    base_dn: dc=example,dc=com
    additional_users_dn: ou=users
    additional_groups_dn: ou=groups
    user: cn=admin,dc=example,dc=com
    password: admin
    attributes:
      username: uid
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    groups_filter: "(member={dn})"

access_control:
  default_policy: deny
  rules:
    - domain: "protected.example.com"
      policy: one_factor

session:
  name: authelia_session
  secret: a_session_secret
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: example.com
      authelia_url: https://auth.example.com

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: a_storage_encryption_key

notifier:
  filesystem:
    filename: /config/notification.txt
